#!/bin/bash

list-credential publish-data-beta > publish-production-secrets.json
list-credential find-data-beta > find-production-secrets.json

list-credential publish-data-beta-staging > publish-staging-secrets.json
list-credential find-data-beta-staging > find-staging-secrets.json
