#!/bin/bash

list-credentials publish-data-beta-production > publish-production-secrets.json
list-credentials find-data-beta > find-production-secrets.json

list-credentials publish-data-beta-staging > publish-staging-secrets.json
list-credentials find-data-beta-staging > find-staging-secrets.json
